config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :additional_services
  resources :booklets, only: [ :index, :show ]
  resources :clients
  resources :invoices, only: [ :show ]
  resources :packages
  resources :plans
  resources :subscriptions
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Welcome to Pay-TV System</h1>

<ul>
  <h3>Clients</h3>
  <li><%= link_to 'Register Client', new_client_path %></li>
  <li><%= link_to 'Show Clients', clients_path %></li>
</ul>

<ul>
  <h3>Plans</h3>
  <li><%= link_to 'Register Plan', new_plan_path %></li>
  <li><%= link_to 'Show Plans', plans_path %></li>
</ul>

<ul>
  <h3>Additional Services</h3>
  <li><%= link_to 'Register Addon', new_additional_service_path %></li>
  <li><%= link_to 'Show Addons', additional_services_path %></li>
</ul>

<ul>
  <h3>Packages</h3>
  <li><%= link_to 'Register Package', new_package_path %></li>
  <li><%= link_to 'Show Packages', packages_path %></li>
</ul>

<ul>
  <h3>Billings</h3>
  <li><%= link_to 'Show Billings', booklets_path %></li>
</ul>