config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :additional_services
  resources :booklets, only: [ :index, :show ]
  resources :clients
  resources :invoices, only: [ :show ]
  resources :packages
  resources :plans
  resources :subscriptions
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :client
  belongs_to :plan, optional: true
  belongs_to :package, optional: true

  has_many :subscription_additional_services, dependent: :destroy
  has_many :additional_services, through: :subscription_additional_services
  has_many :billing_accounts, dependent: :destroy
  has_many :invoices

  has_one :booklet

  validate :must_have_plan_or_package
  validate :addons_only_with_plan

  after_create :generate_billing

  def generate_billing
    BillingAccountsGenerator.new(self).call
    InvoiceGenerator.new(self).call
    BookletGenerator.new(self).call
  end

  private

  def must_have_plan_or_package
    if plan.present? && package.present?
      errors.add(:base, "Subscription should only have a plan or package, not both.")
    elsif plan.blank? && package.blank?
      errors.add(:base, "Subscription must have at least one plan or package")
    end
  end

  def addons_only_with_plan
    if package.present? && additional_services.any?
      errors.add(:base, "Additional services are not allowed when a package is selected")
    end
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  def index
    @subscriptions = Subscription.includes(:plan, :package, :additional_services).all
  end

  def show
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to @subscription, notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to @subscription, notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @subscription.destroy!

    respond_to do |format|
      format.html { redirect_to subscriptions_path, status: :see_other, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_subscription
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:client_id, :plan_id, :package_id, additional_service_ids: [])
  end
end

app/views/subscriptions/_form.html.erb
<%= form_with(model: subscription, local: true) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <p><%= @subscription.errors.full_messages.join(", ") %></p>
    </div>
  <% end %>

  <div>
    <p>
      <%= form.label :client_id, "Client" %><br>
      <%= form.collection_select :client_id, Client.all, :id, :name, prompt: "Select client" %>
    </p>      
  </div>

  <hr>
  <div>
    <p>
      <%= form.label :plan_id, "Plan" %><br>
      <%= form.collection_select :plan_id, Plan.all, :id, :name, include_blank: true %>
    </p>
  </div>

  <div>
    Additional service
    <% AdditionalService.all.each do |service| %>
      <div>
        <%= form.check_box :additional_service_ids, { multiple: true }, service.id, nil %>
        <%= service.name %>
      </div>
    <% end %>  
  </div>
  <hr>

  <div>
    <p>
      <%= form.label :package_id, "Package" %><br>
      <%= form.collection_select :package_id, Package.all, :id, :name, include_blank: true %>
    </p>
  </div>

  <%= form.submit %>
<% end %>

app/views/subscriptions/_subscription.html.erb
<div>
  <h2><%= subscription.client.name %></h2>

  <% if subscription.plan.present? %>
    <p><strong>Plan:</strong> <%= subscription.plan.name %></p>
  <% end %>

  <% if subscription.additional_services.any? %>
    <p><strong>Additional services:</strong></p>
    <ul>
      <% subscription.additional_services.each do |subs| %>
        <li><%= subs.name %></li>
      <% end %>
    </ul>
  <% end %>

  <% if subscription.package.present? %>
    <p><strong>Package:</strong> <%= subscription.package.name %></p>
  <% end %>

</div>

app/views/subscriptions/edit.html.erb
<h1>Editing subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Show this subscription", @subscription %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Subscriptions</h1>

<h3>
  <%= link_to "New subscription", new_subscription_path %>
</h3>

<div id="subscriptions">
  <% @subscriptions.each do |subscription| %>
    <hr>
    <%= render subscription %>
    <p>
      <%= link_to "Show this subscription", subscription %>
    </p>
    <hr>
  <% end %>
</div>

app/views/subscriptions/new.html.erb
<h1>New subscription</h1>

<%= render "form", subscription: @subscription %>

<br>

<div>
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/subscriptions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @subscription %>

<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>

  <p>
    <%= button_to "Destroy this subscription", @subscription, method: :delete %>
  </p>
</div>