config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root to: "home#index"
  resources :additional_services
  resources :booklets, only: [ :index, :show ]
  resources :clients
  resources :invoices, only: [ :show ]
  resources :packages
  resources :plans
  resources :subscriptions
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :packages
  has_many :subscriptions
  has_many :billing_accounts, as: :billable

  validates :name, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :set_plan, only: %i[ show edit update destroy ]

  def index
    @plans = Plan.all
  end

  def show
  end

  def new
    @plan = Plan.new
  end

  def create
    @plan = Plan.new(plan_params)

    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: "Plan was successfully created." }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: "Plan was successfully updated." }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @plan.destroy!

    respond_to do |format|
      format.html { redirect_to plans_path, status: :see_other, notice: "Plan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_plan
    @plan = Plan.find(params[:id])
  end

  def plan_params
    params.require(:plan).permit(:name, :price)
  end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan) do |form| %>
  <% if plan.errors.any? %>
    <div style="color: red">
      <p><%= @plan.errors.full_messages.join(", ") %></p>
    </div>
  <% end %>

  <div>
    <p>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </p>
  </div>

  <div>
    <p>
      <%= form.label :price, style: "display: block" %>
      <%= form.number_field :price, step: 0.01 %>
    </p>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/_plan.html.erb
<div id="<%= dom_id plan %>">
  <p>
    <strong>Plan name:</strong>
    <%= plan.name %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= number_to_currency(plan.price, unit: "R$ ", separator: ",", delimiter: ".") %>
  </p>

</div>

app/views/plans/edit.html.erb
<h1>Editing plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Show this plan", @plan %> |
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Plans</h1>

<h3>
  <%= link_to "New plan", new_plan_path %>
</h3>

<div id="plans">
  <% @plans.each do |plan| %>
    <hr>
    <%= render plan %>
    <p>
      <%= link_to "Show this plan", plan %>
    </p>
    <hr>
  <% end %>
</div>

app/views/plans/new.html.erb
<h1>New plan</h1>

<%= render "form", plan: @plan %>

<br>

<div>
  <%= link_to "Back to plans", plans_path %>
</div>

app/views/plans/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @plan %>

<div>
  <%= link_to "Edit this plan", edit_plan_path(@plan) %> |
  <%= link_to "Back to plans", plans_path %>

  <p>
    <%= button_to "Destroy this plan", @plan, method: :delete %>
  </p>
</div>